"""create initial domain tables

Revision ID: 3d5c121d94ea
Revises:
Create Date: 2026-07-13 18:06:45.565189
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3d5c121d94ea"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("genre", sa.String(length=100), nullable=False),
        sa.Column("premise", sa.Text(), nullable=False),
        sa.Column("target_chapters", sa.Integer(), nullable=False),
        sa.Column("target_words_per_chapter", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "planning",
                "active",
                "completed",
                "archived",
                name="project_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "target_chapters > 0", name=op.f("ck_projects_target_chapters_positive")
        ),
        sa.CheckConstraint(
            "target_words_per_chapter > 0",
            name=op.f("ck_projects_target_words_per_chapter_positive"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_table(
        "chapters",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("chapter_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("outline", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "planned",
                "draft",
                "evaluating",
                "needs_revision",
                "accepted",
                "needs_human_review",
                name="chapter_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.CheckConstraint("chapter_number > 0", name=op.f("ck_chapters_chapter_number_positive")),
        sa.CheckConstraint(
            "score IS NULL OR (score >= 0 AND score <= 100)",
            name=op.f("ck_chapters_chapter_score_range"),
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_chapters_chapter_version_positive")),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_chapters_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chapters")),
        sa.UniqueConstraint("project_id", "chapter_number", name="chapter_project_number"),
    )
    with op.batch_alter_table("chapters", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_chapters_project_id"), ["project_id"], unique=False)

    op.create_table(
        "characters",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("role", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("goals", sa.JSON(), nullable=False),
        sa.Column("personality", sa.Text(), nullable=False),
        sa.Column("speech_style", sa.Text(), nullable=False),
        sa.Column("current_state", sa.Text(), nullable=False),
        sa.Column("secrets", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_characters_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_characters")),
        sa.UniqueConstraint("project_id", "name", name="character_project_name"),
    )
    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_characters_project_id"), ["project_id"], unique=False)

    op.create_table(
        "foreshadowings",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("setup_chapter", sa.Integer(), nullable=False),
        sa.Column("expected_payoff_chapter", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "planned",
                "open",
                "resolved",
                "abandoned",
                name="foreshadowing_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("payoff_chapter", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "expected_payoff_chapter >= setup_chapter",
            name=op.f("ck_foreshadowings_foreshadowing_expected_range"),
        ),
        sa.CheckConstraint(
            "payoff_chapter IS NULL OR payoff_chapter >= setup_chapter",
            name=op.f("ck_foreshadowings_foreshadowing_payoff_range"),
        ),
        sa.CheckConstraint(
            "setup_chapter > 0", name=op.f("ck_foreshadowings_foreshadowing_setup_positive")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_foreshadowings_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_foreshadowings")),
    )
    with op.batch_alter_table("foreshadowings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_foreshadowings_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "locations",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("rules", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_locations_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_locations")),
        sa.UniqueConstraint("project_id", "name", name="location_project_name"),
    )
    with op.batch_alter_table("locations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_locations_project_id"), ["project_id"], unique=False)

    op.create_table(
        "story_rules",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=200), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_story_rules_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_story_rules")),
    )
    with op.batch_alter_table("story_rules", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_story_rules_project_id"), ["project_id"], unique=False)

    op.create_table(
        "evaluations",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("chapter_id", sa.Integer(), nullable=False),
        sa.Column("evaluator", sa.String(length=200), nullable=False),
        sa.Column("overall_score", sa.Float(), nullable=False),
        sa.Column("consistency_score", sa.Float(), nullable=False),
        sa.Column("prose_score", sa.Float(), nullable=False),
        sa.Column("character_score", sa.Float(), nullable=False),
        sa.Column("plot_score", sa.Float(), nullable=False),
        sa.Column("issues", sa.JSON(), nullable=False),
        sa.Column("suggestions", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "character_score >= 0 AND character_score <= 100",
            name=op.f("ck_evaluations_character_score_range"),
        ),
        sa.CheckConstraint(
            "consistency_score >= 0 AND consistency_score <= 100",
            name=op.f("ck_evaluations_consistency_score_range"),
        ),
        sa.CheckConstraint(
            "overall_score >= 0 AND overall_score <= 100",
            name=op.f("ck_evaluations_overall_score_range"),
        ),
        sa.CheckConstraint(
            "plot_score >= 0 AND plot_score <= 100", name=op.f("ck_evaluations_plot_score_range")
        ),
        sa.CheckConstraint(
            "prose_score >= 0 AND prose_score <= 100", name=op.f("ck_evaluations_prose_score_range")
        ),
        sa.ForeignKeyConstraint(
            ["chapter_id"],
            ["chapters.id"],
            name=op.f("fk_evaluations_chapter_id_chapters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_evaluations_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluations")),
    )
    with op.batch_alter_table("evaluations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_evaluations_chapter_id"), ["chapter_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_evaluations_project_id"), ["project_id"], unique=False)

    op.create_table(
        "facts",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("chapter_id", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("predicate", sa.String(length=200), nullable=False),
        sa.Column("object", sa.Text(), nullable=False),
        sa.Column("valid_from_chapter", sa.Integer(), nullable=False),
        sa.Column("valid_to_chapter", sa.Integer(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source_quote", sa.Text(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_facts_fact_confidence_range")
        ),
        sa.CheckConstraint(
            "valid_from_chapter > 0", name=op.f("ck_facts_fact_valid_from_positive")
        ),
        sa.CheckConstraint(
            "valid_to_chapter IS NULL OR valid_to_chapter >= valid_from_chapter",
            name=op.f("ck_facts_fact_valid_range"),
        ),
        sa.ForeignKeyConstraint(
            ["chapter_id"],
            ["chapters.id"],
            name=op.f("fk_facts_chapter_id_chapters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_facts_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_facts")),
    )
    with op.batch_alter_table("facts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_facts_chapter_id"), ["chapter_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_facts_project_id"), ["project_id"], unique=False)

    op.create_table(
        "revisions",
        sa.Column("chapter_id", sa.Integer(), nullable=False),
        sa.Column("previous_version", sa.Integer(), nullable=False),
        sa.Column("new_version", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("score_before", sa.Float(), nullable=False),
        sa.Column("score_after", sa.Float(), nullable=False),
        sa.Column("accepted", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "new_version > previous_version", name=op.f("ck_revisions_revision_version_progression")
        ),
        sa.CheckConstraint(
            "previous_version > 0", name=op.f("ck_revisions_revision_previous_positive")
        ),
        sa.CheckConstraint(
            "score_after >= 0 AND score_after <= 100",
            name=op.f("ck_revisions_revision_score_after_range"),
        ),
        sa.CheckConstraint(
            "score_before >= 0 AND score_before <= 100",
            name=op.f("ck_revisions_revision_score_before_range"),
        ),
        sa.ForeignKeyConstraint(
            ["chapter_id"],
            ["chapters.id"],
            name=op.f("fk_revisions_chapter_id_chapters"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_revisions")),
        sa.UniqueConstraint("chapter_id", "new_version", name="revision_chapter_new_version"),
    )
    with op.batch_alter_table("revisions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_revisions_chapter_id"), ["chapter_id"], unique=False)

    op.create_table(
        "workflow_runs",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("chapter_id", sa.Integer(), nullable=False),
        sa.Column("current_node", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "succeeded",
                "failed",
                "needs_human_review",
                name="workflow_run_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "finished_at IS NULL OR finished_at >= started_at",
            name=op.f("ck_workflow_runs_workflow_finished_after_start"),
        ),
        sa.CheckConstraint(
            "retry_count >= 0", name=op.f("ck_workflow_runs_workflow_retry_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["chapter_id"],
            ["chapters.id"],
            name=op.f("fk_workflow_runs_chapter_id_chapters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_workflow_runs_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_runs")),
    )
    with op.batch_alter_table("workflow_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_workflow_runs_chapter_id"), ["chapter_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_workflow_runs_project_id"), ["project_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workflow_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workflow_runs_project_id"))
        batch_op.drop_index(batch_op.f("ix_workflow_runs_chapter_id"))

    op.drop_table("workflow_runs")
    with op.batch_alter_table("revisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_revisions_chapter_id"))

    op.drop_table("revisions")
    with op.batch_alter_table("facts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_facts_project_id"))
        batch_op.drop_index(batch_op.f("ix_facts_chapter_id"))

    op.drop_table("facts")
    with op.batch_alter_table("evaluations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evaluations_project_id"))
        batch_op.drop_index(batch_op.f("ix_evaluations_chapter_id"))

    op.drop_table("evaluations")
    with op.batch_alter_table("story_rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_story_rules_project_id"))

    op.drop_table("story_rules")
    with op.batch_alter_table("locations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_locations_project_id"))

    op.drop_table("locations")
    with op.batch_alter_table("foreshadowings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_foreshadowings_project_id"))

    op.drop_table("foreshadowings")
    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_characters_project_id"))

    op.drop_table("characters")
    with op.batch_alter_table("chapters", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chapters_project_id"))

    op.drop_table("chapters")
    op.drop_table("projects")
    # ### end Alembic commands ###
