"""add milestone 12 full book workflow

Revision ID: 3f86e80e0e51
Revises: b61d3f7a2c10
Create Date: 2026-07-19 11:37:32.421628
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3f86e80e0e51"
down_revision: str | None = "b61d3f7a2c10"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _backup_sqlite_job_events() -> bool:
    """Protect M11 audit events from SQLite parent-table batch replacement."""
    if op.get_bind().dialect.name != "sqlite":
        return False
    op.execute("DROP TABLE IF EXISTS temp.m12_job_events_backup")
    op.execute("CREATE TEMP TABLE m12_job_events_backup AS SELECT * FROM job_events")
    return True


def _restore_sqlite_job_events(backed_up: bool) -> None:
    if not backed_up:
        return
    op.execute(
        "INSERT INTO job_events "
        "(id, job_id, sequence, event_type, status, step, progress, message_code, message, "
        "attempt, worker_id, workflow_event_id, created_at) "
        "SELECT id, job_id, sequence, event_type, status, step, progress, message_code, message, "
        "attempt, worker_id, workflow_event_id, created_at FROM m12_job_events_backup"
    )
    op.execute("DROP TABLE temp.m12_job_events_backup")


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book_runs",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "planning_validation",
                "generating",
                "paused",
                "global_review",
                "global_revision",
                "completed",
                "completed_needs_review",
                "cancel_requested",
                "cancelled",
                "failed",
                "budget_blocked",
                name="book_run_status",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "mode",
            sa.Enum(
                "sequential",
                "dependency_aware",
                name="book_run_mode",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("thread_id", sa.String(length=36), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("total_chapters", sa.Integer(), nullable=False),
        sa.Column("completed_chapters", sa.Integer(), nullable=False),
        sa.Column("accepted_chapters", sa.Integer(), nullable=False),
        sa.Column("failed_chapters", sa.Integer(), nullable=False),
        sa.Column("needs_review_chapters", sa.Integer(), nullable=False),
        sa.Column("current_chapter_number", sa.Integer(), nullable=True),
        sa.Column("max_chapter_retries", sa.Integer(), nullable=False),
        sa.Column("max_global_revision_rounds", sa.Integer(), nullable=False),
        sa.Column("current_global_revision_round", sa.Integer(), nullable=False),
        sa.Column(
            "model_profile",
            sa.Enum(
                "offline",
                "economy",
                "balanced",
                "quality",
                name="book_run_model_profile",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "privacy_policy",
            sa.Enum(
                "offline",
                "strict",
                "standard",
                name="book_run_privacy_policy",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("budget_id", sa.Integer(), nullable=True),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("workflow_run_id", sa.Integer(), nullable=True),
        sa.Column("book_snapshot_id", sa.Integer(), nullable=True),
        sa.Column("best_snapshot_id", sa.Integer(), nullable=True),
        sa.Column("current_node", sa.String(length=100), nullable=False),
        sa.Column("node_history", sa.JSON(), nullable=False),
        sa.Column("blocking_reasons", sa.JSON(), nullable=False),
        sa.Column("chapter_job_map", sa.JSON(), nullable=False),
        sa.Column("chapter_status_map", sa.JSON(), nullable=False),
        sa.Column("impacted_chapters", sa.JSON(), nullable=False),
        sa.Column("periodic_checks", sa.JSON(), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("max_estimated_cost", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("max_total_tokens", sa.Integer(), nullable=False),
        sa.Column("max_provider_calls", sa.Integer(), nullable=False),
        sa.Column("spent_cost", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("used_tokens", sa.Integer(), nullable=False),
        sa.Column("provider_calls", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "accepted_chapters >= 0", name=op.f("ck_book_runs_book_run_accepted_non_negative")
        ),
        sa.CheckConstraint(
            "completed_chapters >= 0", name=op.f("ck_book_runs_book_run_completed_non_negative")
        ),
        sa.CheckConstraint(
            "current_global_revision_round >= 0",
            name=op.f("ck_book_runs_book_run_revision_round_non_negative"),
        ),
        sa.CheckConstraint(
            "failed_chapters >= 0", name=op.f("ck_book_runs_book_run_failed_non_negative")
        ),
        sa.CheckConstraint(
            "max_global_revision_rounds >= 0",
            name=op.f("ck_book_runs_book_run_max_revision_non_negative"),
        ),
        sa.CheckConstraint(
            "needs_review_chapters >= 0", name=op.f("ck_book_runs_book_run_review_non_negative")
        ),
        sa.CheckConstraint(
            "progress >= 0 AND progress <= 100", name=op.f("ck_book_runs_book_run_progress_range")
        ),
        sa.CheckConstraint(
            "total_chapters > 0", name=op.f("ck_book_runs_book_run_total_chapters_positive")
        ),
        sa.ForeignKeyConstraint(
            ["budget_id"],
            ["project_budgets.id"],
            name=op.f("fk_book_runs_budget_id_project_budgets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name="fk_book_runs_job_id_jobs",
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_book_runs_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_run_id"],
            ["workflow_runs.id"],
            name=op.f("fk_book_runs_workflow_run_id_workflow_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_book_runs")),
        sa.UniqueConstraint("job_id", name=op.f("uq_book_runs_job_id")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_book_runs_idempotency_key")),
        sa.UniqueConstraint("thread_id", name=op.f("uq_book_runs_thread_id")),
    )
    with op.batch_alter_table("book_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_book_runs_project_id"), ["project_id"], unique=False)
        batch_op.create_index(
            "uq_book_runs_active_project",
            ["project_id"],
            unique=True,
            sqlite_where=sa.text(
                "status IN ('pending','planning_validation','generating','paused','global_review','global_revision','cancel_requested','budget_blocked')"
            ),
            postgresql_where=sa.text(
                "status IN ('pending','planning_validation','generating','paused','global_review','global_revision','cancel_requested','budget_blocked')"
            ),
        )

    op.create_table(
        "book_snapshots",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("book_run_id", sa.Integer(), nullable=False),
        sa.Column("snapshot_number", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "candidate",
                "reviewed",
                "accepted",
                "superseded",
                "needs_review",
                name="book_snapshot_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("chapter_version_map", sa.JSON(), nullable=False),
        sa.Column("total_words", sa.Integer(), nullable=False),
        sa.Column("chapter_count", sa.Integer(), nullable=False),
        sa.Column("accepted_chapter_count", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("evaluation_summary", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "chapter_count >= 0",
            name=op.f("ck_book_snapshots_book_snapshot_chapter_count_non_negative"),
        ),
        sa.CheckConstraint(
            "snapshot_number > 0", name=op.f("ck_book_snapshots_book_snapshot_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["book_run_id"],
            ["book_runs.id"],
            name=op.f("fk_book_snapshots_book_run_id_book_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_book_snapshots_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_book_snapshots")),
        sa.UniqueConstraint("book_run_id", "content_hash", name="book_snapshot_run_hash"),
        sa.UniqueConstraint("book_run_id", "snapshot_number", name="book_snapshot_run_number"),
    )
    with op.batch_alter_table("book_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_book_snapshots_book_run_id"), ["book_run_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_book_snapshots_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "book_evaluations",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("book_run_id", sa.Integer(), nullable=False),
        sa.Column("book_snapshot_id", sa.Integer(), nullable=False),
        sa.Column("evaluation_version", sa.Integer(), nullable=False),
        sa.Column("final_score", sa.Float(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("dimension_scores", sa.JSON(), nullable=False),
        sa.Column("blocking_reasons", sa.JSON(), nullable=False),
        sa.Column("recommended_action", sa.String(length=32), nullable=False),
        sa.Column("priority_chapters", sa.JSON(), nullable=False),
        sa.Column("global_issues", sa.JSON(), nullable=False),
        sa.Column("critique", sa.JSON(), nullable=False),
        sa.Column("evaluator_versions", sa.JSON(), nullable=False),
        sa.Column("prompt_versions", sa.JSON(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "final_score >= 0 AND final_score <= 10",
            name=op.f("ck_book_evaluations_book_eval_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["book_run_id"],
            ["book_runs.id"],
            name=op.f("fk_book_evaluations_book_run_id_book_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["book_snapshot_id"],
            ["book_snapshots.id"],
            name=op.f("fk_book_evaluations_book_snapshot_id_book_snapshots"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_book_evaluations_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_book_evaluations")),
        sa.UniqueConstraint("book_snapshot_id", "evaluation_version", name="book_eval_version"),
        sa.UniqueConstraint("idempotency_key", name="book_eval_idempotency"),
    )
    with op.batch_alter_table("book_evaluations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_book_evaluations_book_run_id"), ["book_run_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_book_evaluations_book_snapshot_id"), ["book_snapshot_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_book_evaluations_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "book_revision_plans",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("book_run_id", sa.Integer(), nullable=False),
        sa.Column("book_snapshot_id", sa.Integer(), nullable=False),
        sa.Column("revision_round", sa.Integer(), nullable=False),
        sa.Column("global_objectives", sa.JSON(), nullable=False),
        sa.Column("dependency_order", sa.JSON(), nullable=False),
        sa.Column("must_preserve", sa.JSON(), nullable=False),
        sa.Column("global_constraints", sa.JSON(), nullable=False),
        sa.Column("estimated_calls", sa.Integer(), nullable=False),
        sa.Column("estimated_tokens", sa.Integer(), nullable=False),
        sa.Column("estimated_cost", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "completed",
                "skipped",
                "failed",
                name="book_revision_plan_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "revision_round > 0", name=op.f("ck_book_revision_plans_book_revision_round_positive")
        ),
        sa.ForeignKeyConstraint(
            ["book_run_id"],
            ["book_runs.id"],
            name=op.f("fk_book_revision_plans_book_run_id_book_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["book_snapshot_id"],
            ["book_snapshots.id"],
            name=op.f("fk_book_revision_plans_book_snapshot_id_book_snapshots"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_book_revision_plans_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_book_revision_plans")),
        sa.UniqueConstraint("book_run_id", "revision_round", name="book_revision_run_round"),
    )
    with op.batch_alter_table("book_revision_plans", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_book_revision_plans_book_run_id"), ["book_run_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_book_revision_plans_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "chapter_transition_evaluations",
        sa.Column("book_snapshot_id", sa.Integer(), nullable=False),
        sa.Column("from_chapter", sa.Integer(), nullable=False),
        sa.Column("to_chapter", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("issues", sa.JSON(), nullable=False),
        sa.Column("strengths", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "score >= 0 AND score <= 10",
            name=op.f("ck_chapter_transition_evaluations_transition_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["book_snapshot_id"],
            ["book_snapshots.id"],
            name=op.f("fk_chapter_transition_evaluations_book_snapshot_id_book_snapshots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chapter_transition_evaluations")),
        sa.UniqueConstraint(
            "book_snapshot_id", "from_chapter", "to_chapter", name="transition_snapshot_pair"
        ),
    )
    with op.batch_alter_table("chapter_transition_evaluations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_chapter_transition_evaluations_book_snapshot_id"),
            ["book_snapshot_id"],
            unique=False,
        )

    op.create_table(
        "character_arc_points",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("book_snapshot_id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("chapter_number", sa.Integer(), nullable=False),
        sa.Column("chapter_version_id", sa.Integer(), nullable=False),
        sa.Column("goals", sa.JSON(), nullable=False),
        sa.Column("emotional_state", sa.String(length=200), nullable=False),
        sa.Column("physical_state", sa.String(length=200), nullable=False),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("relationships", sa.JSON(), nullable=False),
        sa.Column("knowledge", sa.JSON(), nullable=False),
        sa.Column("conflicts", sa.JSON(), nullable=False),
        sa.Column("decisions", sa.JSON(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_snapshot_id"],
            ["book_snapshots.id"],
            name=op.f("fk_character_arc_points_book_snapshot_id_book_snapshots"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["chapter_version_id"],
            ["chapter_versions.id"],
            name=op.f("fk_character_arc_points_chapter_version_id_chapter_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
            name=op.f("fk_character_arc_points_character_id_characters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_character_arc_points_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_character_arc_points")),
        sa.UniqueConstraint(
            "book_snapshot_id",
            "character_id",
            "chapter_number",
            name="character_arc_snapshot_character_chapter",
        ),
    )
    with op.batch_alter_table("character_arc_points", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_character_arc_points_book_snapshot_id"),
            ["book_snapshot_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_character_arc_points_character_id"), ["character_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_character_arc_points_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "timeline_events",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("book_snapshot_id", sa.Integer(), nullable=False),
        sa.Column("chapter_id", sa.Integer(), nullable=False),
        sa.Column("chapter_version_id", sa.Integer(), nullable=False),
        sa.Column("event_key", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("story_time", sa.String(length=100), nullable=True),
        sa.Column("sequence_index", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=True),
        sa.Column("participant_entity_ids", sa.JSON(), nullable=False),
        sa.Column("causes_event_ids", sa.JSON(), nullable=False),
        sa.Column("consequence_event_ids", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_timeline_events_timeline_confidence_range"),
        ),
        sa.CheckConstraint(
            "sequence_index >= 0", name=op.f("ck_timeline_events_timeline_sequence_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["book_snapshot_id"],
            ["book_snapshots.id"],
            name=op.f("fk_timeline_events_book_snapshot_id_book_snapshots"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["chapter_id"],
            ["chapters.id"],
            name=op.f("fk_timeline_events_chapter_id_chapters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["chapter_version_id"],
            ["chapter_versions.id"],
            name=op.f("fk_timeline_events_chapter_version_id_chapter_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name=op.f("fk_timeline_events_location_id_locations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_timeline_events_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_timeline_events")),
        sa.UniqueConstraint("book_snapshot_id", "event_key", name="timeline_snapshot_event_key"),
    )
    with op.batch_alter_table("timeline_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_timeline_events_book_snapshot_id"), ["book_snapshot_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_timeline_events_chapter_id"), ["chapter_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_timeline_events_chapter_version_id"),
            ["chapter_version_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_timeline_events_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "book_revision_tasks",
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("chapter_number", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("issue_codes", sa.JSON(), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("required_changes", sa.JSON(), nullable=False),
        sa.Column("preserve_facts", sa.JSON(), nullable=False),
        sa.Column("affected_future_chapters", sa.JSON(), nullable=False),
        sa.Column("rerun_global_checks", sa.JSON(), nullable=False),
        sa.Column("dependency_order", sa.Integer(), nullable=False),
        sa.Column(
            "impact_status",
            sa.Enum(
                "unaffected",
                "recheck_required",
                "revision_required",
                name="chapter_impact_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "completed",
                "skipped",
                "failed",
                name="book_revision_task_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_book_revision_tasks_job_id_jobs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["book_revision_plans.id"],
            name=op.f("fk_book_revision_tasks_plan_id_book_revision_plans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_book_revision_tasks")),
        sa.UniqueConstraint("plan_id", "chapter_number", name="book_revision_task_plan_chapter"),
    )
    with op.batch_alter_table("book_revision_tasks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_book_revision_tasks_plan_id"), ["plan_id"], unique=False
        )

    op.create_table(
        "character_knowledge",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("book_snapshot_id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("fact_id", sa.Integer(), nullable=False),
        sa.Column("learned_chapter", sa.Integer(), nullable=False),
        sa.Column("source_event_id", sa.Integer(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "known",
                "forgotten",
                "misled",
                "false_belief",
                name="character_knowledge_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_character_knowledge_knowledge_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["book_snapshot_id"],
            ["book_snapshots.id"],
            name=op.f("fk_character_knowledge_book_snapshot_id_book_snapshots"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
            name=op.f("fk_character_knowledge_character_id_characters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["fact_id"],
            ["facts.id"],
            name=op.f("fk_character_knowledge_fact_id_facts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_character_knowledge_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_event_id"],
            ["timeline_events.id"],
            name=op.f("fk_character_knowledge_source_event_id_timeline_events"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_character_knowledge")),
        sa.UniqueConstraint(
            "book_snapshot_id", "character_id", "fact_id", name="knowledge_snapshot_character_fact"
        ),
    )
    with op.batch_alter_table("character_knowledge", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_character_knowledge_book_snapshot_id"),
            ["book_snapshot_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_character_knowledge_character_id"), ["character_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_character_knowledge_fact_id"), ["fact_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_character_knowledge_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "relationship_history",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("book_snapshot_id", sa.Integer(), nullable=False),
        sa.Column("subject_character_id", sa.Integer(), nullable=False),
        sa.Column("object_character_id", sa.Integer(), nullable=False),
        sa.Column("relationship_type", sa.String(length=32), nullable=False),
        sa.Column("value", sa.String(length=100), nullable=False),
        sa.Column("chapter_number", sa.Integer(), nullable=False),
        sa.Column("chapter_version_id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("valid_from_chapter", sa.Integer(), nullable=False),
        sa.Column("valid_to_chapter", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "valid_to_chapter IS NULL OR valid_to_chapter >= valid_from_chapter",
            name=op.f("ck_relationship_history_relationship_valid_range"),
        ),
        sa.ForeignKeyConstraint(
            ["book_snapshot_id"],
            ["book_snapshots.id"],
            name=op.f("fk_relationship_history_book_snapshot_id_book_snapshots"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["chapter_version_id"],
            ["chapter_versions.id"],
            name=op.f("fk_relationship_history_chapter_version_id_chapter_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["timeline_events.id"],
            name=op.f("fk_relationship_history_event_id_timeline_events"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["object_character_id"],
            ["characters.id"],
            name=op.f("fk_relationship_history_object_character_id_characters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_relationship_history_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subject_character_id"],
            ["characters.id"],
            name=op.f("fk_relationship_history_subject_character_id_characters"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_relationship_history")),
        sa.UniqueConstraint(
            "book_snapshot_id",
            "subject_character_id",
            "object_character_id",
            "relationship_type",
            "valid_from_chapter",
            name="relationship_snapshot_pair_type_chapter",
        ),
    )
    with op.batch_alter_table("relationship_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_relationship_history_book_snapshot_id"),
            ["book_snapshot_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_relationship_history_project_id"), ["project_id"], unique=False
        )

    job_events_backed_up = _backup_sqlite_job_events()
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("ck_jobs_job_type"), type_="check")
        batch_op.add_column(sa.Column("book_run_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("parent_job_id", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("event_sequence", sa.Integer(), server_default="0", nullable=False)
        )
        batch_op.create_index(batch_op.f("ix_jobs_book_run_id"), ["book_run_id"], unique=False)
        batch_op.create_index("ix_jobs_book_run_status", ["book_run_id", "status"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_parent_job_id"), ["parent_job_id"], unique=False)
        batch_op.create_foreign_key(
            batch_op.f("fk_jobs_book_run_id_book_runs"),
            "book_runs",
            ["book_run_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_jobs_parent_job_id_jobs"),
            "jobs",
            ["parent_job_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_jobs_job_type"),
            "job_type IN ('generate_plan','generate_chapter','evaluate_chapter',"
            "'run_chapter_workflow','resume_workflow','reindex_memory',"
            "'run_retrieval_warmup','run_book','resume_book')",
        )
    _restore_sqlite_job_events(job_events_backed_up)
    op.execute(
        "UPDATE jobs SET event_sequence = COALESCE("
        "(SELECT MAX(job_events.sequence) FROM job_events WHERE job_events.job_id = jobs.id), 0)"
    )
    # ``use_alter`` breaks the intentional BookRun <-> Job cycle. SQLite
    # renders that constraint inline, while PostgreSQL requires the deferred
    # side to be emitted explicitly after the jobs table has been extended.
    if op.get_bind().dialect.name == "postgresql":
        op.create_foreign_key(
            "fk_book_runs_job_id_jobs",
            "book_runs",
            "jobs",
            ["job_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("provider_calls", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("ck_provider_calls_provider_task_type"), type_="check")
        batch_op.create_check_constraint(
            batch_op.f("ck_provider_calls_provider_task_type"),
            "task_type IN ('planning','chapter_drafting','fact_extraction',"
            "'graph_extraction','literary_critique','revision','version_comparison',"
            "'embedding_document','embedding_query','book_critique')",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("provider_calls", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("ck_provider_calls_provider_task_type"), type_="check")
        batch_op.create_check_constraint(
            batch_op.f("ck_provider_calls_provider_task_type"),
            "task_type IN ('planning','chapter_drafting','fact_extraction',"
            "'graph_extraction','literary_critique','revision','version_comparison',"
            "'embedding_document','embedding_query')",
        )

    job_events_backed_up = _backup_sqlite_job_events()
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("ck_jobs_job_type"), type_="check")
        batch_op.drop_constraint(batch_op.f("fk_jobs_parent_job_id_jobs"), type_="foreignkey")
        batch_op.drop_constraint(batch_op.f("fk_jobs_book_run_id_book_runs"), type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_jobs_parent_job_id"))
        batch_op.drop_index("ix_jobs_book_run_status")
        batch_op.drop_index(batch_op.f("ix_jobs_book_run_id"))
        batch_op.drop_column("event_sequence")
        batch_op.drop_column("parent_job_id")
        batch_op.drop_column("book_run_id")
        batch_op.create_check_constraint(
            batch_op.f("ck_jobs_job_type"),
            "job_type IN ('generate_plan','generate_chapter','evaluate_chapter',"
            "'run_chapter_workflow','resume_workflow','reindex_memory',"
            "'run_retrieval_warmup')",
        )
    _restore_sqlite_job_events(job_events_backed_up)

    with op.batch_alter_table("relationship_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_relationship_history_project_id"))
        batch_op.drop_index(batch_op.f("ix_relationship_history_book_snapshot_id"))

    op.drop_table("relationship_history")
    with op.batch_alter_table("character_knowledge", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_character_knowledge_project_id"))
        batch_op.drop_index(batch_op.f("ix_character_knowledge_fact_id"))
        batch_op.drop_index(batch_op.f("ix_character_knowledge_character_id"))
        batch_op.drop_index(batch_op.f("ix_character_knowledge_book_snapshot_id"))

    op.drop_table("character_knowledge")
    with op.batch_alter_table("book_revision_tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_book_revision_tasks_plan_id"))

    op.drop_table("book_revision_tasks")
    with op.batch_alter_table("timeline_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_timeline_events_project_id"))
        batch_op.drop_index(batch_op.f("ix_timeline_events_chapter_version_id"))
        batch_op.drop_index(batch_op.f("ix_timeline_events_chapter_id"))
        batch_op.drop_index(batch_op.f("ix_timeline_events_book_snapshot_id"))

    op.drop_table("timeline_events")
    with op.batch_alter_table("character_arc_points", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_character_arc_points_project_id"))
        batch_op.drop_index(batch_op.f("ix_character_arc_points_character_id"))
        batch_op.drop_index(batch_op.f("ix_character_arc_points_book_snapshot_id"))

    op.drop_table("character_arc_points")
    with op.batch_alter_table("chapter_transition_evaluations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chapter_transition_evaluations_book_snapshot_id"))

    op.drop_table("chapter_transition_evaluations")
    with op.batch_alter_table("book_revision_plans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_book_revision_plans_project_id"))
        batch_op.drop_index(batch_op.f("ix_book_revision_plans_book_run_id"))

    op.drop_table("book_revision_plans")
    with op.batch_alter_table("book_evaluations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_book_evaluations_project_id"))
        batch_op.drop_index(batch_op.f("ix_book_evaluations_book_snapshot_id"))
        batch_op.drop_index(batch_op.f("ix_book_evaluations_book_run_id"))

    op.drop_table("book_evaluations")
    with op.batch_alter_table("book_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_book_snapshots_project_id"))
        batch_op.drop_index(batch_op.f("ix_book_snapshots_book_run_id"))

    op.drop_table("book_snapshots")
    with op.batch_alter_table("book_runs", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_book_runs_active_project",
            sqlite_where=sa.text(
                "status IN ('pending','planning_validation','generating','paused','global_review','global_revision','cancel_requested','budget_blocked')"
            ),
            postgresql_where=sa.text(
                "status IN ('pending','planning_validation','generating','paused','global_review','global_revision','cancel_requested','budget_blocked')"
            ),
        )
        batch_op.drop_index(batch_op.f("ix_book_runs_project_id"))

    op.drop_table("book_runs")
    # ### end Alembic commands ###
