"""add milestone 5 revision workflow

Revision ID: 69c75316dd7e
Revises: ad6fd0f94186
Create Date: 2026-07-14 01:49:31.698796
"""

import re
from collections.abc import Sequence
from hashlib import sha256

import sqlalchemy as sa
from alembic import op

revision: str = "69c75316dd7e"
down_revision: str | None = "ad6fd0f94186"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_M4_CHAPTER_STATUS = sa.Enum(
    "planned",
    "generating",
    "draft",
    "extracting_facts",
    "generated",
    "fact_extraction_failed",
    "failed",
    "evaluating",
    "evaluated_passed",
    "evaluated_needs_revision",
    "evaluation_failed",
    "needs_revision",
    "accepted",
    "needs_human_review",
    name="chapter_status",
    native_enum=False,
    create_constraint=True,
    length=32,
)
_M5_CHAPTER_STATUS = sa.Enum(
    *_M4_CHAPTER_STATUS.enums,
    "workflow_running",
    "drafting",
    "revising",
    "workflow_failed",
    name="chapter_status",
    native_enum=False,
    create_constraint=True,
    length=32,
)
_M4_WORKFLOW_STATUS = sa.Enum(
    "pending",
    "running",
    "succeeded",
    "failed",
    "needs_human_review",
    name="workflow_run_status",
    native_enum=False,
    create_constraint=True,
    length=32,
)
_M5_WORKFLOW_STATUS = sa.Enum(
    *_M4_WORKFLOW_STATUS.enums,
    "paused",
    "completed",
    "completed_needs_review",
    "cancelled",
    name="workflow_run_status",
    native_enum=False,
    create_constraint=True,
    length=32,
)


def _set_sqlite_foreign_keys(*, enabled: bool) -> None:
    connection = op.get_bind()
    if connection.dialect.name == "sqlite":
        connection.exec_driver_sql(f"PRAGMA foreign_keys={'ON' if enabled else 'OFF'}")


def _fact_hash(subject: str, predicate: str, object_value: str) -> str:
    punctuation = re.compile(
        r"[\s,，。.!！?？;；:：'\"“”‘’（）()\[\]{}]+"  # noqa: RUF001
    )
    normalized = [
        punctuation.sub("", value.casefold()).strip()
        for value in (subject, predicate.replace("_", ""), object_value)
    ]
    return sha256("\x1f".join(normalized).encode("utf-8")).hexdigest()


def upgrade() -> None:
    """Apply this revision."""
    _set_sqlite_foreign_keys(enabled=False)
    with op.batch_alter_table("chapters", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=_M4_CHAPTER_STATUS,
            type_=_M5_CHAPTER_STATUS,
            existing_nullable=False,
        )
    with op.batch_alter_table("workflow_runs", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=_M4_WORKFLOW_STATUS,
            type_=_M5_WORKFLOW_STATUS,
            existing_nullable=False,
        )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "version_comparisons",
        sa.Column("workflow_run_id", sa.Integer(), nullable=False),
        sa.Column("old_version_id", sa.Integer(), nullable=False),
        sa.Column("new_version_id", sa.Integer(), nullable=False),
        sa.Column("dimensions", sa.JSON(), nullable=False),
        sa.Column("overall_delta", sa.Float(), nullable=False),
        sa.Column("resolved_issue_codes", sa.JSON(), nullable=False),
        sa.Column("unresolved_issue_codes", sa.JSON(), nullable=False),
        sa.Column("newly_introduced_issue_codes", sa.JSON(), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_version_comparisons_comparison_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["new_version_id"],
            ["chapter_versions.id"],
            name=op.f("fk_version_comparisons_new_version_id_chapter_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["old_version_id"],
            ["chapter_versions.id"],
            name=op.f("fk_version_comparisons_old_version_id_chapter_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_run_id"],
            ["workflow_runs.id"],
            name=op.f("fk_version_comparisons_workflow_run_id_workflow_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_version_comparisons")),
        sa.UniqueConstraint(
            "workflow_run_id", "new_version_id", name="version_comparison_workflow_new"
        ),
    )
    with op.batch_alter_table("version_comparisons", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_version_comparisons_new_version_id"), ["new_version_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_version_comparisons_old_version_id"), ["old_version_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_version_comparisons_workflow_run_id"), ["workflow_run_id"], unique=False
        )

    op.create_table(
        "workflow_events",
        sa.Column("workflow_run_id", sa.Integer(), nullable=False),
        sa.Column("node", sa.String(length=100), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "node_started",
                "node_completed",
                "node_failed",
                "route_selected",
                "version_created",
                "evaluation_created",
                "revision_rejected",
                "version_accepted",
                "workflow_completed",
                name="workflow_event_type",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("version_id", sa.Integer(), nullable=True),
        sa.Column("evaluation_id", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "attempt >= 0", name=op.f("ck_workflow_events_workflow_event_attempt_non_negative")
        ),
        sa.CheckConstraint(
            "duration_ms >= 0", name=op.f("ck_workflow_events_workflow_event_duration_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["evaluations.id"],
            name=op.f("fk_workflow_events_evaluation_id_evaluations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["chapter_versions.id"],
            name=op.f("fk_workflow_events_version_id_chapter_versions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_run_id"],
            ["workflow_runs.id"],
            name=op.f("fk_workflow_events_workflow_run_id_workflow_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_events")),
        sa.UniqueConstraint(
            "workflow_run_id", "node", "event_type", "attempt", name="workflow_event_idempotency"
        ),
    )
    with op.batch_alter_table("workflow_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_workflow_events_workflow_run_id"), ["workflow_run_id"], unique=False
        )

    with op.batch_alter_table("chapter_versions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "status",
                sa.Enum(
                    "draft",
                    "evaluated",
                    "revision",
                    "accepted",
                    "rejected",
                    "superseded",
                    "needs_review",
                    name="chapter_version_status",
                    native_enum=False,
                    create_constraint=True,
                    length=32,
                ),
                server_default="draft",
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("source", sa.String(length=32), server_default="legacy", nullable=False)
        )
        batch_op.add_column(sa.Column("parent_version_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("workflow_run_id", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("word_count", sa.Integer(), server_default="0", nullable=False)
        )
        batch_op.add_column(
            sa.Column("provider", sa.String(length=100), server_default="legacy", nullable=False)
        )
        batch_op.add_column(
            sa.Column("model", sa.String(length=200), server_default="legacy", nullable=False)
        )
        batch_op.add_column(
            sa.Column("prompt_versions", sa.JSON(), server_default="{}", nullable=False)
        )
        batch_op.add_column(
            sa.Column("candidate_character_updates", sa.JSON(), server_default="[]", nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "candidate_foreshadowing_updates", sa.JSON(), server_default="[]", nullable=False
            )
        )
        batch_op.add_column(sa.Column("idempotency_key", sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.create_unique_constraint("chapter_version_idempotency_key", ["idempotency_key"])
        batch_op.create_index(
            batch_op.f("ix_chapter_versions_parent_version_id"), ["parent_version_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_chapter_versions_workflow_run_id"), ["workflow_run_id"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_chapter_versions_parent_version_id_chapter_versions"),
            "chapter_versions",
            ["parent_version_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_chapter_versions_workflow_run_id_workflow_runs"),
            "workflow_runs",
            ["workflow_run_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("chapters", schema=None) as batch_op:
        batch_op.add_column(sa.Column("current_version_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("accepted_version_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_chapters_accepted_version_id_chapter_versions"),
            "chapter_versions",
            ["accepted_version_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_chapters_current_version_id_chapter_versions"),
            "chapter_versions",
            ["current_version_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("consistency_conflicts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("chapter_version_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_consistency_conflicts_chapter_version_id"),
            ["chapter_version_id"],
            unique=False,
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_consistency_conflicts_chapter_version_id_chapter_versions"),
            "chapter_versions",
            ["chapter_version_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("evaluations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("chapter_version_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("workflow_run_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("idempotency_key", sa.String(length=200), nullable=True))
        batch_op.create_unique_constraint("evaluation_idempotency_key", ["idempotency_key"])
        batch_op.create_index(
            batch_op.f("ix_evaluations_chapter_version_id"), ["chapter_version_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_evaluations_workflow_run_id"), ["workflow_run_id"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_evaluations_workflow_run_id_workflow_runs"),
            "workflow_runs",
            ["workflow_run_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_evaluations_chapter_version_id_chapter_versions"),
            "chapter_versions",
            ["chapter_version_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("facts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("chapter_version_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("workflow_run_id", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "status",
                sa.Enum(
                    "candidate",
                    "accepted",
                    "rejected",
                    "superseded",
                    name="fact_status",
                    native_enum=False,
                    create_constraint=True,
                    length=32,
                ),
                server_default="accepted",
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("normalized_hash", sa.String(length=64), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_facts_chapter_version_id"), ["chapter_version_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_facts_workflow_run_id"), ["workflow_run_id"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_facts_chapter_version_id_chapter_versions"),
            "chapter_versions",
            ["chapter_version_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_facts_workflow_run_id_workflow_runs"),
            "workflow_runs",
            ["workflow_run_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("revisions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("source_version_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("new_version_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("workflow_run_id", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("status", sa.String(length=32), server_default="legacy", nullable=False)
        )
        batch_op.add_column(sa.Column("brief", sa.JSON(), server_default="{}", nullable=False))
        batch_op.add_column(
            sa.Column("prompt_versions", sa.JSON(), server_default="{}", nullable=False)
        )
        batch_op.create_index(
            batch_op.f("ix_revisions_new_version_id"), ["new_version_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_revisions_source_version_id"), ["source_version_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_revisions_workflow_run_id"), ["workflow_run_id"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_revisions_new_version_id_chapter_versions"),
            "chapter_versions",
            ["new_version_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_revisions_workflow_run_id_workflow_runs"),
            "workflow_runs",
            ["workflow_run_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_revisions_source_version_id_chapter_versions"),
            "chapter_versions",
            ["source_version_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("workflow_runs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "workflow_type", sa.String(length=50), server_default="legacy", nullable=False
            )
        )
        batch_op.add_column(
            sa.Column("operation", sa.String(length=50), server_default="legacy", nullable=False)
        )
        batch_op.add_column(sa.Column("thread_id", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("original_version_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("current_version_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("best_version_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("accepted_version_id", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("revision_attempt", sa.Integer(), server_default="0", nullable=False)
        )
        batch_op.add_column(
            sa.Column("max_revision_attempts", sa.Integer(), server_default="0", nullable=False)
        )
        batch_op.add_column(
            sa.Column("node_history", sa.JSON(), server_default="[]", nullable=False)
        )
        batch_op.add_column(
            sa.Column("blocking_reasons", sa.JSON(), server_default="[]", nullable=False)
        )
        batch_op.add_column(sa.Column("error_code", sa.String(length=100), nullable=True))
        batch_op.add_column(
            sa.Column("prompt_versions", sa.JSON(), server_default="{}", nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_workflow_runs_best_version_id_chapter_versions"),
            "chapter_versions",
            ["best_version_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_workflow_runs_original_version_id_chapter_versions"),
            "chapter_versions",
            ["original_version_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_workflow_runs_accepted_version_id_chapter_versions"),
            "chapter_versions",
            ["accepted_version_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_workflow_runs_current_version_id_chapter_versions"),
            "chapter_versions",
            ["current_version_id"],
            ["id"],
            ondelete="SET NULL",
        )

    connection = op.get_bind()
    connection.execute(
        sa.text(
            """
            INSERT INTO chapter_versions (
                chapter_id, version, title, content, summary, generation_metadata,
                status, source, word_count, provider, model, prompt_versions,
                candidate_character_updates, candidate_foreshadowing_updates, created_at
            )
            SELECT c.id, c.version, c.title, c.content, COALESCE(c.summary, ''),
                   c.generation_metadata, 'accepted', 'legacy', LENGTH(c.content),
                   'legacy', 'legacy', '{}', '[]', '[]', CURRENT_TIMESTAMP
            FROM chapters AS c
            WHERE NOT EXISTS (
                  SELECT 1 FROM chapter_versions AS cv
                  WHERE cv.chapter_id = c.id AND cv.version = c.version
              )
            """
        )
    )
    connection.execute(
        sa.text(
            """
            UPDATE chapter_versions
            SET status = 'accepted', source = COALESCE(source, 'legacy'),
                provider = COALESCE(provider, 'legacy'), model = COALESCE(model, 'legacy'),
                prompt_versions = COALESCE(prompt_versions, '{}'),
                candidate_character_updates = COALESCE(candidate_character_updates, '[]'),
                candidate_foreshadowing_updates = COALESCE(candidate_foreshadowing_updates, '[]'),
                word_count = CASE WHEN word_count = 0 THEN LENGTH(content) ELSE word_count END,
                accepted_at = COALESCE(accepted_at, created_at)
            """
        )
    )
    connection.execute(
        sa.text(
            """
            UPDATE chapters
            SET current_version_id = (
                    SELECT cv.id FROM chapter_versions AS cv
                    WHERE cv.chapter_id = chapters.id
                    ORDER BY cv.version DESC LIMIT 1
                ),
                accepted_version_id = (
                    SELECT cv.id FROM chapter_versions AS cv
                    WHERE cv.chapter_id = chapters.id
                    ORDER BY cv.version DESC LIMIT 1
                )
            WHERE EXISTS (
                SELECT 1 FROM chapter_versions AS cv WHERE cv.chapter_id = chapters.id
            )
            """
        )
    )
    connection.execute(
        sa.text(
            """
            UPDATE facts
            SET chapter_version_id = (
                    SELECT c.current_version_id FROM chapters AS c WHERE c.id = facts.chapter_id
                ),
                status = 'accepted'
            """
        )
    )
    fact_rows = connection.execute(
        sa.text("SELECT id, chapter_version_id, subject, predicate, object FROM facts ORDER BY id")
    ).mappings()
    seen_hashes: set[tuple[int, str]] = set()
    for row in fact_rows:
        version_id = int(row["chapter_version_id"])
        normalized_hash = _fact_hash(str(row["subject"]), str(row["predicate"]), str(row["object"]))
        key = (version_id, normalized_hash)
        if key in seen_hashes:
            normalized_hash = sha256(f"{normalized_hash}:{row['id']}".encode()).hexdigest()
        seen_hashes.add((version_id, normalized_hash))
        connection.execute(
            sa.text("UPDATE facts SET normalized_hash = :hash WHERE id = :id"),
            {"hash": normalized_hash, "id": row["id"]},
        )
    connection.execute(
        sa.text(
            """
            UPDATE evaluations
            SET chapter_version_id = (
                SELECT c.current_version_id FROM chapters AS c WHERE c.id = evaluations.chapter_id
            )
            """
        )
    )
    connection.execute(
        sa.text(
            """
            UPDATE consistency_conflicts
            SET chapter_version_id = (
                SELECT e.chapter_version_id FROM evaluations AS e
                WHERE e.id = consistency_conflicts.evaluation_id
            )
            """
        )
    )
    connection.execute(
        sa.text(
            """
            UPDATE revisions
            SET source_version_id = (
                    SELECT cv.id FROM chapter_versions AS cv
                    WHERE cv.chapter_id = revisions.chapter_id
                      AND cv.version = revisions.previous_version
                ),
                new_version_id = (
                    SELECT cv.id FROM chapter_versions AS cv
                    WHERE cv.chapter_id = revisions.chapter_id
                      AND cv.version = revisions.new_version
                )
            """
        )
    )
    connection.execute(
        sa.text(
            """
            UPDATE workflow_runs
            SET thread_id = 'legacy-' || id,
                original_version_id = (
                    SELECT c.current_version_id FROM chapters AS c
                    WHERE c.id = workflow_runs.chapter_id
                ),
                current_version_id = (
                    SELECT c.current_version_id FROM chapters AS c
                    WHERE c.id = workflow_runs.chapter_id
                ),
                best_version_id = (
                    SELECT c.current_version_id FROM chapters AS c
                    WHERE c.id = workflow_runs.chapter_id
                ),
                accepted_version_id = (
                    SELECT c.accepted_version_id FROM chapters AS c
                    WHERE c.id = workflow_runs.chapter_id
                )
            """
        )
    )

    with op.batch_alter_table("consistency_conflicts", schema=None) as batch_op:
        batch_op.alter_column("chapter_version_id", existing_type=sa.Integer(), nullable=False)
    with op.batch_alter_table("evaluations", schema=None) as batch_op:
        batch_op.alter_column("chapter_version_id", existing_type=sa.Integer(), nullable=False)
    with op.batch_alter_table("facts", schema=None) as batch_op:
        batch_op.alter_column("chapter_version_id", existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column("normalized_hash", existing_type=sa.String(64), nullable=False)
        batch_op.alter_column(
            "status", existing_type=sa.String(32), nullable=False, server_default=None
        )
        batch_op.create_unique_constraint(
            "fact_version_normalized_hash", ["chapter_version_id", "normalized_hash"]
        )
    with op.batch_alter_table("chapter_versions", schema=None) as batch_op:
        batch_op.alter_column(
            "status", existing_type=sa.String(32), nullable=False, server_default=None
        )
        for name, column_type in (
            ("source", sa.String(32)),
            ("word_count", sa.Integer()),
            ("provider", sa.String(100)),
            ("model", sa.String(200)),
            ("prompt_versions", sa.JSON()),
            ("candidate_character_updates", sa.JSON()),
            ("candidate_foreshadowing_updates", sa.JSON()),
        ):
            batch_op.alter_column(
                name, existing_type=column_type, nullable=False, server_default=None
            )
    with op.batch_alter_table("revisions", schema=None) as batch_op:
        for name, column_type in (
            ("status", sa.String(32)),
            ("brief", sa.JSON()),
            ("prompt_versions", sa.JSON()),
        ):
            batch_op.alter_column(
                name, existing_type=column_type, nullable=False, server_default=None
            )
    with op.batch_alter_table("workflow_runs", schema=None) as batch_op:
        batch_op.alter_column("thread_id", existing_type=sa.String(64), nullable=False)
        batch_op.create_unique_constraint(batch_op.f("uq_workflow_runs_thread_id"), ["thread_id"])
        for name, column_type in (
            ("workflow_type", sa.String(50)),
            ("operation", sa.String(50)),
            ("revision_attempt", sa.Integer()),
            ("max_revision_attempts", sa.Integer()),
            ("node_history", sa.JSON()),
            ("blocking_reasons", sa.JSON()),
            ("prompt_versions", sa.JSON()),
        ):
            batch_op.alter_column(
                name, existing_type=column_type, nullable=False, server_default=None
            )

    _set_sqlite_foreign_keys(enabled=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    _set_sqlite_foreign_keys(enabled=False)
    connection = op.get_bind()
    connection.execute(sa.text("DELETE FROM facts WHERE status <> 'accepted'"))
    connection.execute(
        sa.text(
            """
            UPDATE workflow_runs
            SET status = CASE status
                WHEN 'completed' THEN 'succeeded'
                WHEN 'completed_needs_review' THEN 'needs_human_review'
                WHEN 'paused' THEN 'failed'
                WHEN 'cancelled' THEN 'failed'
                ELSE status
            END
            """
        )
    )
    connection.execute(
        sa.text(
            """
            UPDATE chapters
            SET status = CASE status
                WHEN 'workflow_running' THEN 'generated'
                WHEN 'drafting' THEN 'draft'
                WHEN 'revising' THEN 'needs_revision'
                WHEN 'workflow_failed' THEN 'failed'
                ELSE status
            END
            """
        )
    )
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workflow_runs", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_workflow_runs_current_version_id_chapter_versions"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_workflow_runs_accepted_version_id_chapter_versions"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_workflow_runs_original_version_id_chapter_versions"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_workflow_runs_best_version_id_chapter_versions"), type_="foreignkey"
        )
        batch_op.drop_constraint(batch_op.f("uq_workflow_runs_thread_id"), type_="unique")
        batch_op.drop_column("updated_at")
        batch_op.drop_column("prompt_versions")
        batch_op.drop_column("error_code")
        batch_op.drop_column("blocking_reasons")
        batch_op.drop_column("node_history")
        batch_op.drop_column("max_revision_attempts")
        batch_op.drop_column("revision_attempt")
        batch_op.drop_column("accepted_version_id")
        batch_op.drop_column("best_version_id")
        batch_op.drop_column("current_version_id")
        batch_op.drop_column("original_version_id")
        batch_op.drop_column("thread_id")
        batch_op.drop_column("operation")
        batch_op.drop_column("workflow_type")

    with op.batch_alter_table("revisions", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_revisions_source_version_id_chapter_versions"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_revisions_workflow_run_id_workflow_runs"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_revisions_new_version_id_chapter_versions"), type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_revisions_workflow_run_id"))
        batch_op.drop_index(batch_op.f("ix_revisions_source_version_id"))
        batch_op.drop_index(batch_op.f("ix_revisions_new_version_id"))
        batch_op.drop_column("prompt_versions")
        batch_op.drop_column("brief")
        batch_op.drop_column("status")
        batch_op.drop_column("workflow_run_id")
        batch_op.drop_column("new_version_id")
        batch_op.drop_column("source_version_id")

    facts_copy = sa.Table("facts", sa.MetaData(), autoload_with=connection)
    for constraint in list(facts_copy.constraints):
        if isinstance(constraint, sa.CheckConstraint) and "status" in str(constraint.sqltext):
            facts_copy.constraints.remove(constraint)
    with op.batch_alter_table("facts", schema=None, copy_from=facts_copy) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_facts_workflow_run_id_workflow_runs"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_facts_chapter_version_id_chapter_versions"), type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_facts_workflow_run_id"))
        batch_op.drop_index(batch_op.f("ix_facts_chapter_version_id"))
        batch_op.drop_constraint("fact_version_normalized_hash", type_="unique")
        batch_op.drop_column("normalized_hash")
        batch_op.drop_column("status")
        batch_op.drop_column("workflow_run_id")
        batch_op.drop_column("chapter_version_id")

    with op.batch_alter_table("evaluations", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_evaluations_chapter_version_id_chapter_versions"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_evaluations_workflow_run_id_workflow_runs"), type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_evaluations_workflow_run_id"))
        batch_op.drop_index(batch_op.f("ix_evaluations_chapter_version_id"))
        batch_op.drop_constraint("evaluation_idempotency_key", type_="unique")
        batch_op.drop_column("idempotency_key")
        batch_op.drop_column("workflow_run_id")
        batch_op.drop_column("chapter_version_id")

    with op.batch_alter_table("consistency_conflicts", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_consistency_conflicts_chapter_version_id_chapter_versions"),
            type_="foreignkey",
        )
        batch_op.drop_index(batch_op.f("ix_consistency_conflicts_chapter_version_id"))
        batch_op.drop_column("chapter_version_id")

    with op.batch_alter_table("chapters", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_chapters_current_version_id_chapter_versions"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_chapters_accepted_version_id_chapter_versions"), type_="foreignkey"
        )
        batch_op.drop_column("accepted_version_id")
        batch_op.drop_column("current_version_id")

    versions_copy = sa.Table("chapter_versions", sa.MetaData(), autoload_with=connection)
    for constraint in list(versions_copy.constraints):
        if isinstance(constraint, sa.CheckConstraint) and "status" in str(constraint.sqltext):
            versions_copy.constraints.remove(constraint)
    with op.batch_alter_table("chapter_versions", schema=None, copy_from=versions_copy) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_chapter_versions_workflow_run_id_workflow_runs"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_chapter_versions_parent_version_id_chapter_versions"), type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_chapter_versions_workflow_run_id"))
        batch_op.drop_index(batch_op.f("ix_chapter_versions_parent_version_id"))
        batch_op.drop_constraint("chapter_version_idempotency_key", type_="unique")
        batch_op.drop_column("accepted_at")
        batch_op.drop_column("idempotency_key")
        batch_op.drop_column("candidate_foreshadowing_updates")
        batch_op.drop_column("candidate_character_updates")
        batch_op.drop_column("prompt_versions")
        batch_op.drop_column("model")
        batch_op.drop_column("provider")
        batch_op.drop_column("word_count")
        batch_op.drop_column("workflow_run_id")
        batch_op.drop_column("parent_version_id")
        batch_op.drop_column("source")
        batch_op.drop_column("status")

    with op.batch_alter_table("workflow_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workflow_events_workflow_run_id"))

    op.drop_table("workflow_events")
    with op.batch_alter_table("version_comparisons", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_version_comparisons_workflow_run_id"))
        batch_op.drop_index(batch_op.f("ix_version_comparisons_old_version_id"))
        batch_op.drop_index(batch_op.f("ix_version_comparisons_new_version_id"))

    op.drop_table("version_comparisons")
    with op.batch_alter_table("workflow_runs", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=_M5_WORKFLOW_STATUS,
            type_=_M4_WORKFLOW_STATUS,
            existing_nullable=False,
        )
    with op.batch_alter_table("chapters", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=_M5_CHAPTER_STATUS,
            type_=_M4_CHAPTER_STATUS,
            existing_nullable=False,
        )
    _set_sqlite_foreign_keys(enabled=True)
    # ### end Alembic commands ###
