"""Repository interfaces for StoryForge persistence."""

from storyforge.repositories.base import PageSlice, Repository
from storyforge.repositories.books import (
    ACTIVE_BOOK_RUN_STATUSES,
    BookEvaluationRepository,
    BookRevisionPlanRepository,
    BookRunRepository,
    BookSnapshotRepository,
    ChapterTransitionRepository,
    CharacterArcRepository,
    CharacterKnowledgeRepository,
    RelationshipHistoryRepository,
    TimelineEventRepository,
)
from storyforge.repositories.domain import (
    ChapterRepository,
    ChapterVersionRepository,
    CharacterRepository,
    ConflictRepository,
    DemoAuditRepository,
    EvaluationIssueRepository,
    EvaluationRepository,
    FactRepository,
    ForeshadowingRepository,
    LocationRepository,
    ProjectRepository,
    RevisionRepository,
    StoryRuleRepository,
    SystemRepository,
    VersionComparisonRepository,
    WorkflowEventRepository,
    WorkflowRunRepository,
)
from storyforge.repositories.jobs import (
    ACTIVE_JOB_STATUSES,
    JobEventRepository,
    JobRepository,
    OutboxRepository,
    WorkerRepository,
)

__all__ = [
    "ACTIVE_BOOK_RUN_STATUSES",
    "ACTIVE_JOB_STATUSES",
    "BookEvaluationRepository",
    "BookRevisionPlanRepository",
    "BookRunRepository",
    "BookSnapshotRepository",
    "ChapterRepository",
    "ChapterTransitionRepository",
    "ChapterVersionRepository",
    "CharacterArcRepository",
    "CharacterKnowledgeRepository",
    "CharacterRepository",
    "ConflictRepository",
    "DemoAuditRepository",
    "EvaluationIssueRepository",
    "EvaluationRepository",
    "FactRepository",
    "ForeshadowingRepository",
    "JobEventRepository",
    "JobRepository",
    "LocationRepository",
    "OutboxRepository",
    "PageSlice",
    "ProjectRepository",
    "RelationshipHistoryRepository",
    "Repository",
    "RevisionRepository",
    "StoryRuleRepository",
    "SystemRepository",
    "TimelineEventRepository",
    "VersionComparisonRepository",
    "WorkerRepository",
    "WorkflowEventRepository",
    "WorkflowRunRepository",
]
