"""Repository interfaces for StoryForge persistence."""

from storyforge.repositories.base import PageSlice, Repository
from storyforge.repositories.domain import (
    ChapterRepository,
    ChapterVersionRepository,
    CharacterRepository,
    ConflictRepository,
    DemoAuditRepository,
    EvaluationIssueRepository,
    EvaluationRepository,
    FactRepository,
    ForeshadowingRepository,
    LocationRepository,
    ProjectRepository,
    RevisionRepository,
    StoryRuleRepository,
    SystemRepository,
    VersionComparisonRepository,
    WorkflowEventRepository,
    WorkflowRunRepository,
)
from storyforge.repositories.jobs import (
    ACTIVE_JOB_STATUSES,
    JobEventRepository,
    JobRepository,
    OutboxRepository,
    WorkerRepository,
)

__all__ = [
    "ACTIVE_JOB_STATUSES",
    "ChapterRepository",
    "ChapterVersionRepository",
    "CharacterRepository",
    "ConflictRepository",
    "DemoAuditRepository",
    "EvaluationIssueRepository",
    "EvaluationRepository",
    "FactRepository",
    "ForeshadowingRepository",
    "JobEventRepository",
    "JobRepository",
    "LocationRepository",
    "OutboxRepository",
    "PageSlice",
    "ProjectRepository",
    "Repository",
    "RevisionRepository",
    "StoryRuleRepository",
    "SystemRepository",
    "VersionComparisonRepository",
    "WorkerRepository",
    "WorkflowEventRepository",
    "WorkflowRunRepository",
]
